// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250918063946_d")]
    partial class d
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.Property<Guid>("AIFeedBackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("longtext");

                    b.Property<int>("FluencyScore")
                        .HasColumnType("int");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("int");

                    b.Property<int>("PronunciationScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("int");

                    b.HasKey("AIFeedBackID");

                    b.HasIndex("ConversationID");

                    b.ToTable("AIFeedBacks");
                });

            modelBuilder.Entity("DAL.Models.Achievement", b =>
                {
                    b.Property<Guid>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Critertia")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementID = new Guid("a1370cd0-9f8d-4d53-ae8e-ba0a747d4590"),
                            Critertia = "Complete 1 lesson",
                            Description = "Complete your first lesson",
                            IconUrl = "🎯",
                            Title = "First Steps"
                        },
                        new
                        {
                            AchievementID = new Guid("56aae191-004a-4356-b9fe-9612c9355a1f"),
                            Critertia = "Complete 1 course",
                            Description = "Complete your first course",
                            IconUrl = "🏆",
                            Title = "Course Completion"
                        },
                        new
                        {
                            AchievementID = new Guid("1fe0a2d9-2ab3-4d24-b363-1a8eb29e2a7b"),
                            Critertia = "7 consecutive days of learning",
                            Description = "Maintain a 7-day learning streak",
                            IconUrl = "🔥",
                            Title = "Week Warrior"
                        });
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("AIFeedBackID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ConversationID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApprovedByID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumLessons")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CourseID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.Property<Guid>("CourseSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ReviewBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("SubmitterUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseSubmissionID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SubmitterUserID");

                    b.ToTable("CourseSubmissions");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.Property<Guid>("CourseTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseTopicID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TopicID")
                        .IsUnique();

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Property<Guid>("CourseUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CourseUnitID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseUnits");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Hints")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExerciseID");

                    b.HasIndex("LessonID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = new Guid("b225740d-7c5c-4de0-a196-83d6405517db"),
                            CreateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            LanguageCode = "EN",
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageID = new Guid("15fb35b9-a104-4efe-ab6a-a542bbd72ea5"),
                            CreateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            LanguageCode = "JP",
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageID = new Guid("d696a74c-2e22-45e0-b81f-820bcfea2d82"),
                            CreateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            LanguageCode = "ZH",
                            LanguageName = "Chinese"
                        });
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("CourseUnitID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("IsPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseUnitID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Property<Guid>("PurchasesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.Property<Guid>("PurchasesDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("PurchasesID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesDetailID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PurchasesID");

                    b.ToTable("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.Property<Guid>("RecordingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConverationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RecordingID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DAL.Models.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.Property<Guid>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReportedCourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedLessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ReportID");

                    b.HasIndex("ReportedCourseID");

                    b.HasIndex("ReportedLessonID");

                    b.HasIndex("ReportedUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Property<Guid>("RoadmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RoadmapID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.Property<Guid>("RoadmapDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoadmapID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoadmapDetailID");

                    b.HasIndex("RoadmapID", "StepNumber")
                        .IsUnique();

                    b.ToTable("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("c7957c0e-a79c-484e-9b11-a7a0c6360fa7"),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Description = "System administrator with full access",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("26783bd9-52ba-4388-8e00-a9bcc1668022"),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Description = "Staff member for specific language support",
                            Name = "Staff"
                        },
                        new
                        {
                            RoleID = new Guid("170397fd-92d8-4db0-bf04-f0459cba3868"),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Description = "Teacher who can create and manage courses",
                            Name = "Teacher"
                        },
                        new
                        {
                            RoleID = new Guid("d312450c-6a8b-430a-a54e-56b32ff2c6bc"),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Description = "Student learning languages",
                            Name = "Learner"
                        });
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Property<Guid>("TeacherApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SubmitAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeacherCredentialID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherApplicationID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherApplications");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.Property<Guid>("TeacherCredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApplicationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialFileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherCredentialID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.TempRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TempRegistrations");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Property<Guid>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicID = new Guid("ad6e7520-fe87-49bc-ab83-980addee0edb"),
                            Description = "Basic and advanced grammar concepts",
                            Name = "Grammar"
                        },
                        new
                        {
                            TopicID = new Guid("e864b8b0-fffe-44a8-ac02-6b049d2e033c"),
                            Description = "Essential vocabulary for daily communication",
                            Name = "Vocabulary"
                        },
                        new
                        {
                            TopicID = new Guid("e4158acd-d368-4e00-ab74-cdb432774b43"),
                            Description = "Practical conversation skills and dialogues",
                            Name = "Conversation"
                        },
                        new
                        {
                            TopicID = new Guid("3744893a-9ca0-480c-88dc-17ced5e300dc"),
                            Description = "Pronunciation and speaking skills",
                            Name = "Pronunciation"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastAcessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("MfaEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("dce0b328-2ccc-43b5-9e6b-78a6c36a6ca4"),
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Email = "admin@flearn.com",
                            Industry = "Education Technology",
                            Interests = "System Management",
                            IsEmailConfirmed = true,
                            JobTitle = "System Administrator",
                            LastAcessAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            MfaEnabled = false,
                            PasswordHash = "5YReGHJnh1atvSpK9Izx5JO3q9VwI5IEFhaSkez+8r2cnu21O0z8lFi1qHH7WUK2MmuvpyhdzYqBvgFmbcvXKg==",
                            PasswordSalt = "FLykKtzaRC3Xp7+UbQBghnIbXXxoPlarDE5yEUqif67kjBI7GYF8aOvCZ1V59g1JHRIqd88UwqCL48jQCpFhauEWQ/ET9E5tq1sBF7Yn6UThw6PL69/6vI+nP86W3i2T+SLRVo+e23dmmVBGbL+onmE1B/p1DvXy9Wpnw2mUahE=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            UserName = "Flearn"
                        },
                        new
                        {
                            UserID = new Guid("17b560b9-d332-4aea-b8a1-7a90f28b3055"),
                            BirthDate = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Email = "staff.english@flearn.com",
                            Industry = "Education",
                            Interests = "English Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "English Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            MfaEnabled = false,
                            PasswordHash = "b4SV/UcO4AGyONnIaTSLsCieORDEwpfIr290AgL73+8hLm2vEOqeu2IhVTKG3ASswTTaFUopnlNe9YwnVUrUqQ==",
                            PasswordSalt = "V3GDTSWM6caqKKS7YmtyqXVXaoznHplo+a5FMZC39qvjPe0ux+HBejSqDrlJqkk3iITesw1XoftYf4dd1nSV65qeNYDUU9mYM+0Ynf7IXy+rrbX5W5sNd+d1FkYvIsLP2ZWvivc9elS1ccbinV8LpVNnlJm4x76c0zTIhViDzbI=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            UserName = "StaffEN"
                        },
                        new
                        {
                            UserID = new Guid("72757900-03f9-4bf6-9f52-5a030466bbf3"),
                            BirthDate = new DateTime(1991, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Email = "staff.japanese@flearn.com",
                            Industry = "Education",
                            Interests = "Japanese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Japanese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            MfaEnabled = false,
                            PasswordHash = "b4SV/UcO4AGyONnIaTSLsCieORDEwpfIr290AgL73+8hLm2vEOqeu2IhVTKG3ASswTTaFUopnlNe9YwnVUrUqQ==",
                            PasswordSalt = "V3GDTSWM6caqKKS7YmtyqXVXaoznHplo+a5FMZC39qvjPe0ux+HBejSqDrlJqkk3iITesw1XoftYf4dd1nSV65qeNYDUU9mYM+0Ynf7IXy+rrbX5W5sNd+d1FkYvIsLP2ZWvivc9elS1ccbinV8LpVNnlJm4x76c0zTIhViDzbI=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            UserName = "StaffJP"
                        },
                        new
                        {
                            UserID = new Guid("a8ecb768-a4ec-409d-9703-d8feae50fb1f"),
                            BirthDate = new DateTime(1993, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            Email = "staff.chinese@flearn.com",
                            Industry = "Education",
                            Interests = "Chinese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Chinese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            MfaEnabled = false,
                            PasswordHash = "b4SV/UcO4AGyONnIaTSLsCieORDEwpfIr290AgL73+8hLm2vEOqeu2IhVTKG3ASswTTaFUopnlNe9YwnVUrUqQ==",
                            PasswordSalt = "V3GDTSWM6caqKKS7YmtyqXVXaoznHplo+a5FMZC39qvjPe0ux+HBejSqDrlJqkk3iITesw1XoftYf4dd1nSV65qeNYDUU9mYM+0Ynf7IXy+rrbX5W5sNd+d1FkYvIsLP2ZWvivc9elS1ccbinV8LpVNnlJm4x76c0zTIhViDzbI=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 18, 6, 39, 46, 524, DateTimeKind.Utc).AddTicks(655),
                            UserName = "StaffZH"
                        });
                });

            modelBuilder.Entity("DAL.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserAchievementID");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.Property<Guid>("UserLearningLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserLearningLanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLanguages");

                    b.HasData(
                        new
                        {
                            UserLearningLanguageID = new Guid("a7524860-cd8f-4913-934b-f6c8dedeb8ae"),
                            LanguageID = new Guid("b225740d-7c5c-4de0-a196-83d6405517db"),
                            UserID = new Guid("17b560b9-d332-4aea-b8a1-7a90f28b3055")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("7f660073-5648-499d-88df-40ba83e174f8"),
                            LanguageID = new Guid("15fb35b9-a104-4efe-ab6a-a542bbd72ea5"),
                            UserID = new Guid("72757900-03f9-4bf6-9f52-5a030466bbf3")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("5d02ccf1-7238-4ebd-b773-e20bc7af04da"),
                            LanguageID = new Guid("d696a74c-2e22-45e0-b81f-820bcfea2d82"),
                            UserID = new Guid("a8ecb768-a4ec-409d-9703-d8feae50fb1f")
                        });
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleID = new Guid("cf38dfc8-bd04-44a9-80c4-ae790f48c717"),
                            RoleID = new Guid("c7957c0e-a79c-484e-9b11-a7a0c6360fa7"),
                            UserID = new Guid("dce0b328-2ccc-43b5-9e6b-78a6c36a6ca4")
                        },
                        new
                        {
                            UserRoleID = new Guid("7a4cd38b-ccc4-4e69-b921-6a0a81264209"),
                            RoleID = new Guid("26783bd9-52ba-4388-8e00-a9bcc1668022"),
                            UserID = new Guid("17b560b9-d332-4aea-b8a1-7a90f28b3055")
                        },
                        new
                        {
                            UserRoleID = new Guid("717420f5-d273-41e6-89f7-373e966326de"),
                            RoleID = new Guid("26783bd9-52ba-4388-8e00-a9bcc1668022"),
                            UserID = new Guid("72757900-03f9-4bf6-9f52-5a030466bbf3")
                        },
                        new
                        {
                            UserRoleID = new Guid("ce98e78e-cafa-4ed3-9941-df440dd425d8"),
                            RoleID = new Guid("26783bd9-52ba-4388-8e00-a9bcc1668022"),
                            UserID = new Guid("a8ecb768-a4ec-409d-9703-d8feae50fb1f")
                        });
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.Property<Guid>("LanguagesLanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("LanguagesLanguageID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("LanguageUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesRoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RolesRoleID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("AIFeedBacks")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Conversations")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Courses")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseSubmissions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterUserID");

                    b.Navigation("Course");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseTopics")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Topic", "Topic")
                        .WithOne("CourseTopics")
                        .HasForeignKey("DAL.Models.CourseTopic", "TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseUnits")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.HasOne("DAL.Models.Course", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.HasOne("DAL.Models.Lesson", "Lesson")
                        .WithMany("Exerices")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.HasOne("DAL.Models.CourseUnit", "CourseUnit")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseUnit");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Purchases", "Purchases")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("PurchasesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("Recordings")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.HasOne("DAL.Models.Course", "ReportedCourse")
                        .WithMany()
                        .HasForeignKey("ReportedCourseID");

                    b.HasOne("DAL.Models.Lesson", "ReportedLesson")
                        .WithMany()
                        .HasForeignKey("ReportedLessonID");

                    b.HasOne("DAL.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserID");

                    b.HasOne("DAL.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedCourse");

                    b.Navigation("ReportedLesson");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Roadmaps")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Roadmaps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.HasOne("DAL.Models.Roadmap", "Roadmap")
                        .WithMany("RoadmapDetails")
                        .HasForeignKey("RoadmapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("TeacherApplications")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.HasOne("DAL.Models.TeacherApplication", "Application")
                        .WithMany("TeacherCredentials")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.HasOne("DAL.Models.User", null)
                        .WithMany("LearningLanguages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.HasOne("DAL.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesLanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Navigation("AIFeedBacks");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Navigation("CourseSubmissions");

                    b.Navigation("CourseTopics");

                    b.Navigation("CourseUnits");

                    b.Navigation("Enrollments");

                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Courses");

                    b.Navigation("Roadmaps");

                    b.Navigation("TeacherApplications");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Navigation("Exerices");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Navigation("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Navigation("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Navigation("CourseTopics")
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("LearningLanguages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roadmaps");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
