// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925003647_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.Property<Guid>("AIFeedBackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("longtext");

                    b.Property<int>("FluencyScore")
                        .HasColumnType("int");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("int");

                    b.Property<int>("PronunciationScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("int");

                    b.HasKey("AIFeedBackID");

                    b.HasIndex("ConversationID");

                    b.ToTable("AIFeedBacks");
                });

            modelBuilder.Entity("DAL.Models.Achievement", b =>
                {
                    b.Property<Guid>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Critertia")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementID = new Guid("fe49651c-37e7-4382-bc47-2de2c25c816d"),
                            Critertia = "Complete 1 lesson",
                            Description = "Complete your first lesson",
                            IconUrl = "🎯",
                            Title = "First Steps"
                        },
                        new
                        {
                            AchievementID = new Guid("e0d226bc-e3d7-40cf-9f45-44203de634a1"),
                            Critertia = "Complete 1 course",
                            Description = "Complete your first course",
                            IconUrl = "🏆",
                            Title = "Course Completion"
                        },
                        new
                        {
                            AchievementID = new Guid("23b7dcc1-329e-43ee-ad9e-e968fe241aa6"),
                            Critertia = "7 consecutive days of learning",
                            Description = "Maintain a 7-day learning streak",
                            IconUrl = "🔥",
                            Title = "Week Warrior"
                        });
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("AIFeedBackID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ConversationID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApprovedByID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumLessons")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CourseID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.Property<Guid>("CourseSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ReviewBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("SubmitterUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseSubmissionID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SubmitterUserID");

                    b.ToTable("CourseSubmissions");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.Property<Guid>("CourseTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseTopicID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TopicID");

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Property<Guid>("CourseUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CourseUnitID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseUnits");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Hints")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExerciseID");

                    b.HasIndex("LessonID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = new Guid("2c5bd7be-5ea2-4c7b-b60b-c6c9300eadfb"),
                            CreateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            LanguageCode = "EN",
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageID = new Guid("7165b3a2-08db-4cb4-bd56-576b39e91306"),
                            CreateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            LanguageCode = "JP",
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageID = new Guid("e6b5e7d4-661f-43f1-8bd0-006d2553b94f"),
                            CreateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            LanguageCode = "ZH",
                            LanguageName = "Chinese"
                        });
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("CourseUnitID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("IsPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseUnitID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DAL.Models.PasswordResetOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Property<Guid>("PurchasesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.Property<Guid>("PurchasesDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("PurchasesID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesDetailID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PurchasesID");

                    b.ToTable("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.Property<Guid>("RecordingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConverationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RecordingID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DAL.Models.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.Property<Guid>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReportedCourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedLessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ReportID");

                    b.HasIndex("ReportedCourseID");

                    b.HasIndex("ReportedLessonID");

                    b.HasIndex("ReportedUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Property<Guid>("RoadmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RoadmapID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.Property<Guid>("RoadmapDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoadmapID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoadmapDetailID");

                    b.HasIndex("RoadmapID", "StepNumber")
                        .IsUnique();

                    b.ToTable("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("d310ae94-23f1-487d-a62d-cf6b5b7a1d91"),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Description = "System administrator with full access",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("19e4f171-3d4e-4d9f-a811-bd0bd0e08cdb"),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Description = "Staff member for specific language support",
                            Name = "Staff"
                        },
                        new
                        {
                            RoleID = new Guid("fdb64d34-dd07-4220-88ac-e95d73fa4d66"),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Description = "Teacher who can create and manage courses",
                            Name = "Teacher"
                        },
                        new
                        {
                            RoleID = new Guid("61e85b5f-99be-4501-9b8d-1394211faeec"),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Description = "Student learning languages",
                            Name = "Learner"
                        });
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Property<Guid>("TeacherApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SubmitAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeacherCredentialID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("TeachingExperience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeachingLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherApplicationID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherApplications");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.Property<Guid>("TeacherCredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApplicationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialFileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherCredentialID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.TempRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TempRegistrations");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Property<Guid>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicID = new Guid("43550bfb-9f88-44a8-9e67-0076527a9d4e"),
                            Description = "Basic and advanced grammar concepts",
                            Name = "Grammar"
                        },
                        new
                        {
                            TopicID = new Guid("d1ba7c2c-e9e8-4545-9c2e-effa21390e21"),
                            Description = "Essential vocabulary for daily communication",
                            Name = "Vocabulary"
                        },
                        new
                        {
                            TopicID = new Guid("9c8fed74-95dc-452f-b5eb-7f3be4d67555"),
                            Description = "Practical conversation skills and dialogues",
                            Name = "Conversation"
                        },
                        new
                        {
                            TopicID = new Guid("8b858937-3f09-4044-ac7a-28e0292aad1d"),
                            Description = "Pronunciation and speaking skills",
                            Name = "Pronunciation"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastAcessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("MfaEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("059b4949-2d15-4509-b05f-2b9e3162a5d7"),
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Email = "admin@flearn.com",
                            Industry = "Education Technology",
                            Interests = "System Management",
                            IsEmailConfirmed = true,
                            JobTitle = "System Administrator",
                            LastAcessAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            MfaEnabled = false,
                            PasswordHash = "IT2i/qo6eOJipLpZWLZVPAr+oIrjHxErUBCJyj6Ayy2ktB6Q1Zi4EaLN3IiGPcqLNVtEO5HJ9ynea2JNsnlqEg==",
                            PasswordSalt = "bhEQN393tDcGwgCb9xSuS4QR1OpEjE4P4mUp+mLnQDw8q7IIBJbgsM8Tk0gQ/iK5PQrisSU4FNSYT8Yaliq8xt9G8hKOvnExtfmGmhl2FC9RajZeeZgDYuRBR76aa03jQ68JEmRuJkQF1mBMsbikMUJ+dAKF11j+x0mLfEU1a1o=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            UserName = "Flearn"
                        },
                        new
                        {
                            UserID = new Guid("86668e44-9695-4f45-b053-5bf3b35e67f9"),
                            BirthDate = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Email = "staff.english@flearn.com",
                            Industry = "Education",
                            Interests = "English Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "English Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            MfaEnabled = false,
                            PasswordHash = "UK+aFFG7MiQhxM9DXOCfu/hYtJ7tuomktSlRIyAvNHgR1Rzm/C/B/n2II7pxa39Ee/9+py/p93HG9OlvfzKSXw==",
                            PasswordSalt = "239Ia5gIZ/TiTWey1zNbo6UXNq5WXD2UaAwe+YP2CLjc7KZHge3+Gj47p8Xxr9wyjZIUhcRULdODMWZ2002VQHmXCY8PlgTMISZAldqhaLl6pvK63EsL6Oa9LUA2hqSBv+2TlXAhozEAt/rU52WdgGn01a5AEMgZ47/CgoUepIw=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            UserName = "StaffEN"
                        },
                        new
                        {
                            UserID = new Guid("94cac57f-f19f-4726-b4e7-ccb075984987"),
                            BirthDate = new DateTime(1991, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Email = "staff.japanese@flearn.com",
                            Industry = "Education",
                            Interests = "Japanese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Japanese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            MfaEnabled = false,
                            PasswordHash = "UK+aFFG7MiQhxM9DXOCfu/hYtJ7tuomktSlRIyAvNHgR1Rzm/C/B/n2II7pxa39Ee/9+py/p93HG9OlvfzKSXw==",
                            PasswordSalt = "239Ia5gIZ/TiTWey1zNbo6UXNq5WXD2UaAwe+YP2CLjc7KZHge3+Gj47p8Xxr9wyjZIUhcRULdODMWZ2002VQHmXCY8PlgTMISZAldqhaLl6pvK63EsL6Oa9LUA2hqSBv+2TlXAhozEAt/rU52WdgGn01a5AEMgZ47/CgoUepIw=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            UserName = "StaffJP"
                        },
                        new
                        {
                            UserID = new Guid("dac2f21d-5f96-4e3e-b720-22d0d810a19d"),
                            BirthDate = new DateTime(1993, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            Email = "staff.chinese@flearn.com",
                            Industry = "Education",
                            Interests = "Chinese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Chinese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            MfaEnabled = false,
                            PasswordHash = "UK+aFFG7MiQhxM9DXOCfu/hYtJ7tuomktSlRIyAvNHgR1Rzm/C/B/n2II7pxa39Ee/9+py/p93HG9OlvfzKSXw==",
                            PasswordSalt = "239Ia5gIZ/TiTWey1zNbo6UXNq5WXD2UaAwe+YP2CLjc7KZHge3+Gj47p8Xxr9wyjZIUhcRULdODMWZ2002VQHmXCY8PlgTMISZAldqhaLl6pvK63EsL6Oa9LUA2hqSBv+2TlXAhozEAt/rU52WdgGn01a5AEMgZ47/CgoUepIw=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 25, 0, 36, 47, 243, DateTimeKind.Utc).AddTicks(6148),
                            UserName = "StaffZH"
                        });
                });

            modelBuilder.Entity("DAL.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserAchievementID");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.Property<Guid>("UserLearningLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserLearningLanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLanguages");

                    b.HasData(
                        new
                        {
                            UserLearningLanguageID = new Guid("e401f49e-8ce5-4654-90af-71cd06852f9e"),
                            LanguageID = new Guid("2c5bd7be-5ea2-4c7b-b60b-c6c9300eadfb"),
                            UserID = new Guid("86668e44-9695-4f45-b053-5bf3b35e67f9")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("f1ab46cd-0c8a-4724-9f83-169cdf50a462"),
                            LanguageID = new Guid("7165b3a2-08db-4cb4-bd56-576b39e91306"),
                            UserID = new Guid("94cac57f-f19f-4726-b4e7-ccb075984987")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("50dd59db-85d8-495d-8970-81420811a5ec"),
                            LanguageID = new Guid("e6b5e7d4-661f-43f1-8bd0-006d2553b94f"),
                            UserID = new Guid("dac2f21d-5f96-4e3e-b720-22d0d810a19d")
                        });
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleID = new Guid("fc087ce1-f6d3-4963-84d0-2fcce6bcf9f3"),
                            RoleID = new Guid("d310ae94-23f1-487d-a62d-cf6b5b7a1d91"),
                            UserID = new Guid("059b4949-2d15-4509-b05f-2b9e3162a5d7")
                        },
                        new
                        {
                            UserRoleID = new Guid("25573809-51f6-45b5-9421-2f88a4426caf"),
                            RoleID = new Guid("19e4f171-3d4e-4d9f-a811-bd0bd0e08cdb"),
                            UserID = new Guid("86668e44-9695-4f45-b053-5bf3b35e67f9")
                        },
                        new
                        {
                            UserRoleID = new Guid("c4017a37-6c51-4d41-a09c-27c4ba27eab6"),
                            RoleID = new Guid("19e4f171-3d4e-4d9f-a811-bd0bd0e08cdb"),
                            UserID = new Guid("94cac57f-f19f-4726-b4e7-ccb075984987")
                        },
                        new
                        {
                            UserRoleID = new Guid("28aa53f6-b3ff-4e37-9d5a-524f069a0141"),
                            RoleID = new Guid("19e4f171-3d4e-4d9f-a811-bd0bd0e08cdb"),
                            UserID = new Guid("dac2f21d-5f96-4e3e-b720-22d0d810a19d")
                        });
                });

            modelBuilder.Entity("DAL.Models.UserSurvey", b =>
                {
                    b.Property<Guid>("SurveyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("AiRecommendations")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InterestedTopics")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LearningReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PreferredAccent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("PreferredLanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("PreferredLearningStyle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PreviousExperience")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("PrioritySkills")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SpeakingChallenges")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetTimeline")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("SurveyID");

                    b.HasIndex("PreferredLanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSurveys");
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.Property<Guid>("LanguagesLanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("LanguagesLanguageID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("LanguageUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesRoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RolesRoleID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("AIFeedBacks")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Conversations")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Courses")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseSubmissions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterUserID");

                    b.Navigation("Course");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseTopics")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Topic", "Topic")
                        .WithMany("CourseTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseUnits")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.HasOne("DAL.Models.Course", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.HasOne("DAL.Models.Lesson", "Lesson")
                        .WithMany("Exerices")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.HasOne("DAL.Models.CourseUnit", "CourseUnit")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseUnit");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Purchases", "Purchases")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("PurchasesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("Recordings")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.HasOne("DAL.Models.Course", "ReportedCourse")
                        .WithMany()
                        .HasForeignKey("ReportedCourseID");

                    b.HasOne("DAL.Models.Lesson", "ReportedLesson")
                        .WithMany()
                        .HasForeignKey("ReportedLessonID");

                    b.HasOne("DAL.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserID");

                    b.HasOne("DAL.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedCourse");

                    b.Navigation("ReportedLesson");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Roadmaps")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Roadmaps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.HasOne("DAL.Models.Roadmap", "Roadmap")
                        .WithMany("RoadmapDetails")
                        .HasForeignKey("RoadmapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("TeacherApplications")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.HasOne("DAL.Models.TeacherApplication", "Application")
                        .WithMany("TeacherCredentials")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.HasOne("DAL.Models.User", null)
                        .WithMany("LearningLanguages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.UserSurvey", b =>
                {
                    b.HasOne("DAL.Models.Language", "PreferredLanguage")
                        .WithMany()
                        .HasForeignKey("PreferredLanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.HasOne("DAL.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesLanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Navigation("AIFeedBacks");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Navigation("CourseSubmissions");

                    b.Navigation("CourseTopics");

                    b.Navigation("CourseUnits");

                    b.Navigation("Enrollments");

                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Courses");

                    b.Navigation("Roadmaps");

                    b.Navigation("TeacherApplications");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Navigation("Exerices");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Navigation("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Navigation("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Navigation("CourseTopics");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("LearningLanguages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roadmaps");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
