// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.Property<Guid>("AIFeedBackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("longtext");

                    b.Property<int>("FluencyScore")
                        .HasColumnType("int");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("int");

                    b.Property<int>("PronunciationScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("int");

                    b.HasKey("AIFeedBackID");

                    b.HasIndex("ConversationID");

                    b.ToTable("AIFeedBacks");
                });

            modelBuilder.Entity("DAL.Models.Achievement", b =>
                {
                    b.Property<Guid>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Critertia")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementID = new Guid("714a25a6-b989-45b9-83e0-4645a7bb4f14"),
                            Critertia = "Complete 1 lesson",
                            Description = "Complete your first lesson",
                            IconUrl = "🎯",
                            Title = "First Steps"
                        },
                        new
                        {
                            AchievementID = new Guid("6fe47c9d-25b4-40d2-834c-c79782f54658"),
                            Critertia = "Complete 1 course",
                            Description = "Complete your first course",
                            IconUrl = "🏆",
                            Title = "Course Completion"
                        },
                        new
                        {
                            AchievementID = new Guid("f7a24c21-1ebc-44df-9f3d-f7bdfdc5b3d9"),
                            Critertia = "7 consecutive days of learning",
                            Description = "Maintain a 7-day learning streak",
                            IconUrl = "🔥",
                            Title = "Week Warrior"
                        });
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("AIFeedBackID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ConversationID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Property<Guid>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApprovedByID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumLessons")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CourseID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.Property<Guid>("CourseSubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ReviewBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("SubmitterUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseSubmissionID");

                    b.HasIndex("CourseID");

                    b.HasIndex("SubmitterUserID");

                    b.ToTable("CourseSubmissions");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.Property<Guid>("CourseTopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("CourseTopicID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TopicID")
                        .IsUnique();

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Property<Guid>("CourseUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CourseUnitID");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseUnits");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.Property<Guid>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Hints")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("LessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExerciseID");

                    b.HasIndex("LessonID");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Property<Guid>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageID = new Guid("9c66299d-bc1f-464e-8189-e55804dbbce0"),
                            CreateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            LanguageCode = "EN",
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageID = new Guid("775ae28a-d00c-42aa-a682-fb28e5da4428"),
                            CreateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            LanguageCode = "JP",
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            LanguageID = new Guid("fbae66d2-2477-4352-9d11-89dea2ae7224"),
                            CreateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            LanguageCode = "ZH",
                            LanguageName = "Chinese"
                        });
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Property<Guid>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("CourseUnitID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("IsPublished")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("SkillFocus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LessonID");

                    b.HasIndex("CourseUnitID");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Property<Guid>("PurchasesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.Property<Guid>("PurchasesDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("PurchasesID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("PurchasesDetailID");

                    b.HasIndex("CourseID");

                    b.HasIndex("PurchasesID");

                    b.ToTable("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.Property<Guid>("RecordingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConverationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ConversationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Duration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RecordingID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DAL.Models.RegistrationOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.ToTable("RegistrationOtps");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.Property<Guid>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReportedCourseID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedLessonID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ReportedUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("ReportID");

                    b.HasIndex("ReportedCourseID");

                    b.HasIndex("ReportedLessonID");

                    b.HasIndex("ReportedUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Property<Guid>("RoadmapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DurationUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<decimal>("Progress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RoadmapID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.Property<Guid>("RoadmapDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resources")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoadmapID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoadmapDetailID");

                    b.HasIndex("RoadmapID", "StepNumber")
                        .IsUnique();

                    b.ToTable("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<Guid>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = new Guid("cbbbf98a-894c-458d-83df-5aad1128a26a"),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Description = "System administrator with full access",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleID = new Guid("5feef0ad-01f5-47bf-986f-f94b7eb05ffd"),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Description = "Staff member for specific language support",
                            Name = "Staff"
                        },
                        new
                        {
                            RoleID = new Guid("e534f22d-84a2-4e6a-86d7-00f120e8bb52"),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Description = "Teacher who can create and manage courses",
                            Name = "Teacher"
                        },
                        new
                        {
                            RoleID = new Guid("cd73ba2f-dfa4-4013-94d7-33a77824ffe2"),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Description = "Student learning languages",
                            Name = "Learner"
                        });
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Property<Guid>("TeacherApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReviewAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SubmitAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TeacherCredentialID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherApplicationID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherApplications");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.Property<Guid>("TeacherCredentialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("ApplicationID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CredentialFileUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CredentialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("TeacherCredentialID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("UserID");

                    b.ToTable("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.TempRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TempRegistrations");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Property<Guid>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicID = new Guid("92f3648c-020d-44ae-a22d-672ffad53caa"),
                            Description = "Basic and advanced grammar concepts",
                            Name = "Grammar"
                        },
                        new
                        {
                            TopicID = new Guid("be3b325a-f2a1-4e9d-9456-395e54d39f23"),
                            Description = "Essential vocabulary for daily communication",
                            Name = "Vocabulary"
                        },
                        new
                        {
                            TopicID = new Guid("abb3214d-cb3d-47fb-9044-bbc89fd9c792"),
                            Description = "Practical conversation skills and dialogues",
                            Name = "Conversation"
                        },
                        new
                        {
                            TopicID = new Guid("1f3f6fa9-ed79-4609-99d8-7c226b3a61ce"),
                            Description = "Pronunciation and speaking skills",
                            Name = "Pronunciation"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Interests")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastAcessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("MfaEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("StreakDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("bae616b9-1391-4e15-b432-e8c226b9aad1"),
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Email = "admin@flearn.com",
                            Industry = "Education Technology",
                            Interests = "System Management",
                            IsEmailConfirmed = true,
                            JobTitle = "System Administrator",
                            LastAcessAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            MfaEnabled = false,
                            PasswordHash = "zqUQ0jn3cQEc2YkipCWQG2XIsEu4oyUIhxGmx/r08KnwpIzzA7S7ZN9HB6hbmFqxUh8pE/Rz2g84Zxj8xeOsAw==",
                            PasswordSalt = "htWHM6rMOySL+BpdqqGl9kElWqLKryn+1+Lmzw+afxzNyeOCgHteK/cqiM/Tcg7c8bcO/HqG1AsL68WXSzrjCvjc6xH4QI5CjA576xoeNZ7LwW/Dwdx5Gl39srLujtyEkMOnWOoj9aQNXyvk8rEFjsVYllgwf4QojF/hQVdA4d0=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            UserName = "Flearn"
                        },
                        new
                        {
                            UserID = new Guid("18c3d30b-f0e1-457d-a189-3f58b3f1ac16"),
                            BirthDate = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Email = "staff.english@flearn.com",
                            Industry = "Education",
                            Interests = "English Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "English Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            MfaEnabled = false,
                            PasswordHash = "RfKZfh/ccqkjuu8hbF569mKVUf2VLjPcKvrpUS+IA4M0VUrk0nQYPgJFxDE65lR8Cja+fwESfFFRa7ZmIYGBIA==",
                            PasswordSalt = "3pOEv1qMev+bI2dHs3V70zewbudLa/liMHawUc/HwMpP84oVGbxQb+sGPP4q23Ov0TEXJyIC1ZBP0++BScUvFfrb7psUIeJ0pCEtz2nxORZjN/QtVFpG+7om/zcVY21FCflNxFx8RR+mrsXX0B0Sk8Ghp5UQTkHNIuJQh7hqkH8=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            UserName = "StaffEN"
                        },
                        new
                        {
                            UserID = new Guid("4433656a-c9d6-4b4c-b887-ff0e043ddd87"),
                            BirthDate = new DateTime(1991, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Email = "staff.japanese@flearn.com",
                            Industry = "Education",
                            Interests = "Japanese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Japanese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            MfaEnabled = false,
                            PasswordHash = "RfKZfh/ccqkjuu8hbF569mKVUf2VLjPcKvrpUS+IA4M0VUrk0nQYPgJFxDE65lR8Cja+fwESfFFRa7ZmIYGBIA==",
                            PasswordSalt = "3pOEv1qMev+bI2dHs3V70zewbudLa/liMHawUc/HwMpP84oVGbxQb+sGPP4q23Ov0TEXJyIC1ZBP0++BScUvFfrb7psUIeJ0pCEtz2nxORZjN/QtVFpG+7om/zcVY21FCflNxFx8RR+mrsXX0B0Sk8Ghp5UQTkHNIuJQh7hqkH8=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            UserName = "StaffJP"
                        },
                        new
                        {
                            UserID = new Guid("3309433c-38ac-4c13-960e-9b7c3986697d"),
                            BirthDate = new DateTime(1993, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            Email = "staff.chinese@flearn.com",
                            Industry = "Education",
                            Interests = "Chinese Language Support",
                            IsEmailConfirmed = true,
                            JobTitle = "Chinese Language Staff",
                            LastAcessAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            MfaEnabled = false,
                            PasswordHash = "RfKZfh/ccqkjuu8hbF569mKVUf2VLjPcKvrpUS+IA4M0VUrk0nQYPgJFxDE65lR8Cja+fwESfFFRa7ZmIYGBIA==",
                            PasswordSalt = "3pOEv1qMev+bI2dHs3V70zewbudLa/liMHawUc/HwMpP84oVGbxQb+sGPP4q23Ov0TEXJyIC1ZBP0++BScUvFfrb7psUIeJ0pCEtz2nxORZjN/QtVFpG+7om/zcVY21FCflNxFx8RR+mrsXX0B0Sk8Ghp5UQTkHNIuJQh7hqkH8=",
                            ProfilePictureUrl = "",
                            Status = true,
                            StreakDays = 0,
                            UpdateAt = new DateTime(2025, 9, 17, 9, 21, 1, 821, DateTimeKind.Utc).AddTicks(8131),
                            UserName = "StaffZH"
                        });
                });

            modelBuilder.Entity("DAL.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserAchievementID");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.Property<Guid>("UserLearningLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("LanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserLearningLanguageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLearningLanguages");

                    b.HasData(
                        new
                        {
                            UserLearningLanguageID = new Guid("e82720f3-77d4-455f-8c8c-c900a4e5a17c"),
                            LanguageID = new Guid("9c66299d-bc1f-464e-8189-e55804dbbce0"),
                            UserID = new Guid("18c3d30b-f0e1-457d-a189-3f58b3f1ac16")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("fb6655c9-1e71-407d-b165-af5c75c97ec0"),
                            LanguageID = new Guid("775ae28a-d00c-42aa-a682-fb28e5da4428"),
                            UserID = new Guid("4433656a-c9d6-4b4c-b887-ff0e043ddd87")
                        },
                        new
                        {
                            UserLearningLanguageID = new Guid("9515a162-0d43-4f88-8bd7-be8958b9eac8"),
                            LanguageID = new Guid("fbae66d2-2477-4352-9d11-89dea2ae7224"),
                            UserID = new Guid("3309433c-38ac-4c13-960e-9b7c3986697d")
                        });
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("UserRoleID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleID = new Guid("57f0649a-e9be-469e-b01e-0c344eb4ae93"),
                            RoleID = new Guid("cbbbf98a-894c-458d-83df-5aad1128a26a"),
                            UserID = new Guid("bae616b9-1391-4e15-b432-e8c226b9aad1")
                        },
                        new
                        {
                            UserRoleID = new Guid("4bbc3816-9558-4592-ad0d-79318571288d"),
                            RoleID = new Guid("5feef0ad-01f5-47bf-986f-f94b7eb05ffd"),
                            UserID = new Guid("18c3d30b-f0e1-457d-a189-3f58b3f1ac16")
                        },
                        new
                        {
                            UserRoleID = new Guid("5eca3776-89a4-4b0f-8df2-4a2590233c5f"),
                            RoleID = new Guid("5feef0ad-01f5-47bf-986f-f94b7eb05ffd"),
                            UserID = new Guid("4433656a-c9d6-4b4c-b887-ff0e043ddd87")
                        },
                        new
                        {
                            UserRoleID = new Guid("d25980e7-5cb8-44e2-93cd-514d6c693c05"),
                            RoleID = new Guid("5feef0ad-01f5-47bf-986f-f94b7eb05ffd"),
                            UserID = new Guid("3309433c-38ac-4c13-960e-9b7c3986697d")
                        });
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.Property<Guid>("LanguagesLanguageID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("LanguagesLanguageID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("LanguageUser");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesRoleID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<Guid>("UsersUserID")
                        .HasColumnType("char(36)")
                        .UseCollation("utf8mb4_general_ci");

                    b.HasKey("RolesRoleID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("DAL.Models.AIFeedBack", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("AIFeedBacks")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Conversations")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Courses")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DAL.Models.CourseSubmission", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseSubmissions")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterUserID");

                    b.Navigation("Course");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("DAL.Models.CourseTopic", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseTopics")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Topic", "Topic")
                        .WithOne("CourseTopics")
                        .HasForeignKey("DAL.Models.CourseTopic", "TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("CourseUnits")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DAL.Models.Enrollment", b =>
                {
                    b.HasOne("DAL.Models.Course", null)
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Exercise", b =>
                {
                    b.HasOne("DAL.Models.Lesson", "Lesson")
                        .WithMany("Exerices")
                        .HasForeignKey("LessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.HasOne("DAL.Models.CourseUnit", "CourseUnit")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseUnit");
                });

            modelBuilder.Entity("DAL.Models.PurchasesDetail", b =>
                {
                    b.HasOne("DAL.Models.Course", "Course")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Purchases", "Purchases")
                        .WithMany("PurchasesDetails")
                        .HasForeignKey("PurchasesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("DAL.Models.Recording", b =>
                {
                    b.HasOne("DAL.Models.Conversation", "Conversation")
                        .WithMany("Recordings")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DAL.Models.RefreshToken", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Report", b =>
                {
                    b.HasOne("DAL.Models.Course", "ReportedCourse")
                        .WithMany()
                        .HasForeignKey("ReportedCourseID");

                    b.HasOne("DAL.Models.Lesson", "ReportedLesson")
                        .WithMany()
                        .HasForeignKey("ReportedLessonID");

                    b.HasOne("DAL.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserID");

                    b.HasOne("DAL.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedCourse");

                    b.Navigation("ReportedLesson");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Roadmaps")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Roadmaps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.RoadmapDetail", b =>
                {
                    b.HasOne("DAL.Models.Roadmap", "Roadmap")
                        .WithMany("RoadmapDetails")
                        .HasForeignKey("RoadmapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.TeacherCredential", b =>
                {
                    b.HasOne("DAL.Models.TeacherApplication", "Application")
                        .WithMany("TeacherCredentials")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.UserLearningLanguage", b =>
                {
                    b.HasOne("DAL.Models.User", null)
                        .WithMany("LearningLanguages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.UserRole", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageUser", b =>
                {
                    b.HasOne("DAL.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesLanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("DAL.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Conversation", b =>
                {
                    b.Navigation("AIFeedBacks");

                    b.Navigation("Recordings");
                });

            modelBuilder.Entity("DAL.Models.Course", b =>
                {
                    b.Navigation("CourseSubmissions");

                    b.Navigation("CourseTopics");

                    b.Navigation("CourseUnits");

                    b.Navigation("Enrollments");

                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.CourseUnit", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Courses");

                    b.Navigation("Roadmaps");
                });

            modelBuilder.Entity("DAL.Models.Lesson", b =>
                {
                    b.Navigation("Exerices");
                });

            modelBuilder.Entity("DAL.Models.Purchases", b =>
                {
                    b.Navigation("PurchasesDetails");
                });

            modelBuilder.Entity("DAL.Models.Roadmap", b =>
                {
                    b.Navigation("RoadmapDetails");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DAL.Models.TeacherApplication", b =>
                {
                    b.Navigation("TeacherCredentials");
                });

            modelBuilder.Entity("DAL.Models.Topic", b =>
                {
                    b.Navigation("CourseTopics")
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("LearningLanguages");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roadmaps");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
